// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "axi_stream_counter_range.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic axi_stream_counter_range::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic axi_stream_counter_range::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<3> axi_stream_counter_range::ap_ST_fsm_state1 = "1";
const sc_lv<3> axi_stream_counter_range::ap_ST_fsm_state2 = "10";
const sc_lv<3> axi_stream_counter_range::ap_ST_fsm_state3 = "100";
const sc_lv<32> axi_stream_counter_range::ap_const_lv32_0 = "00000000000000000000000000000000";
const bool axi_stream_counter_range::ap_const_boolean_1 = true;
const sc_lv<1> axi_stream_counter_range::ap_const_lv1_0 = "0";
const sc_lv<1> axi_stream_counter_range::ap_const_lv1_1 = "1";
const sc_lv<2> axi_stream_counter_range::ap_const_lv2_0 = "00";
const sc_lv<2> axi_stream_counter_range::ap_const_lv2_2 = "10";
const sc_lv<2> axi_stream_counter_range::ap_const_lv2_3 = "11";
const sc_lv<2> axi_stream_counter_range::ap_const_lv2_1 = "1";
const sc_lv<32> axi_stream_counter_range::ap_const_lv32_1 = "1";
const sc_lv<32> axi_stream_counter_range::ap_const_lv32_2 = "10";
const sc_lv<31> axi_stream_counter_range::ap_const_lv31_0 = "0000000000000000000000000000000";
const sc_lv<31> axi_stream_counter_range::ap_const_lv31_1 = "1";

axi_stream_counter_range::axi_stream_counter_range(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_state1);
    sensitive << ( ap_start );
    sensitive << ( count_range_0_vld_out );

    SC_METHOD(thread_ap_block_state2_io);
    sensitive << ( counter_output_1_ack_in );
    sensitive << ( tmp_fu_59_p2 );

    SC_METHOD(thread_ap_done);
    sensitive << ( counter_output_1_ack_in );
    sensitive << ( counter_output_1_state );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_fu_59_p2 );
    sensitive << ( ap_block_state2_io );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( counter_output_1_ack_in );
    sensitive << ( counter_output_1_state );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_fu_59_p2 );
    sensitive << ( ap_block_state2_io );

    SC_METHOD(thread_ap_return);
    sensitive << ( counter_output_1_ack_in );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_fu_59_p2 );
    sensitive << ( ap_block_state2_io );

    SC_METHOD(thread_ap_rst_n_inv);
    sensitive << ( ap_rst_n );

    SC_METHOD(thread_count_range_0_ack_in);
    sensitive << ( count_range_0_state );

    SC_METHOD(thread_count_range_0_ack_out);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( count_range_0_vld_out );

    SC_METHOD(thread_count_range_0_data_out);
    sensitive << ( count_range_0_payload_A );
    sensitive << ( count_range_0_payload_B );
    sensitive << ( count_range_0_sel );

    SC_METHOD(thread_count_range_0_load_A);
    sensitive << ( count_range_0_sel_wr );
    sensitive << ( count_range_0_state_cmp_full );

    SC_METHOD(thread_count_range_0_load_B);
    sensitive << ( count_range_0_sel_wr );
    sensitive << ( count_range_0_state_cmp_full );

    SC_METHOD(thread_count_range_0_sel);
    sensitive << ( count_range_0_sel_rd );

    SC_METHOD(thread_count_range_0_state_cmp_full);
    sensitive << ( count_range_0_state );

    SC_METHOD(thread_count_range_0_vld_in);
    sensitive << ( count_range_TVALID );

    SC_METHOD(thread_count_range_0_vld_out);
    sensitive << ( count_range_0_state );

    SC_METHOD(thread_count_range_TDATA_blk_n);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( count_range_0_state );

    SC_METHOD(thread_count_range_TREADY);
    sensitive << ( count_range_0_state );

    SC_METHOD(thread_counterValue_1_fu_64_p2);
    sensitive << ( counterValue_reg_43 );

    SC_METHOD(thread_counterValue_cast_fu_54_p1);
    sensitive << ( counterValue_reg_43 );

    SC_METHOD(thread_counter_output_1_ack_in);
    sensitive << ( counter_output_1_state );

    SC_METHOD(thread_counter_output_1_ack_out);
    sensitive << ( counter_output_TREADY );

    SC_METHOD(thread_counter_output_1_data_out);
    sensitive << ( counter_output_1_payload_A );
    sensitive << ( counter_output_1_payload_B );
    sensitive << ( counter_output_1_sel );

    SC_METHOD(thread_counter_output_1_load_A);
    sensitive << ( counter_output_1_sel_wr );
    sensitive << ( counter_output_1_state_cmp_full );

    SC_METHOD(thread_counter_output_1_load_B);
    sensitive << ( counter_output_1_sel_wr );
    sensitive << ( counter_output_1_state_cmp_full );

    SC_METHOD(thread_counter_output_1_sel);
    sensitive << ( counter_output_1_sel_rd );

    SC_METHOD(thread_counter_output_1_state_cmp_full);
    sensitive << ( counter_output_1_state );

    SC_METHOD(thread_counter_output_1_vld_in);
    sensitive << ( counter_output_1_ack_in );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_fu_59_p2 );
    sensitive << ( ap_block_state2_io );

    SC_METHOD(thread_counter_output_1_vld_out);
    sensitive << ( counter_output_1_state );

    SC_METHOD(thread_counter_output_TDATA);
    sensitive << ( counter_output_1_data_out );

    SC_METHOD(thread_counter_output_TDATA_blk_n);
    sensitive << ( counter_output_1_state );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_fu_59_p2 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_counter_output_TVALID);
    sensitive << ( counter_output_1_state );

    SC_METHOD(thread_tmp_fu_59_p2);
    sensitive << ( counter_output_1_ack_in );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( count_range_read_reg_70 );
    sensitive << ( counterValue_cast_fu_54_p1 );
    sensitive << ( ap_block_state2_io );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( count_range_0_vld_out );
    sensitive << ( counter_output_1_ack_in );
    sensitive << ( counter_output_1_state );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_fu_59_p2 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_block_state2_io );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    ap_CS_fsm = "001";
    count_range_0_sel_rd = SC_LOGIC_0;
    count_range_0_sel_wr = SC_LOGIC_0;
    count_range_0_state = "00";
    counter_output_1_sel_rd = SC_LOGIC_0;
    counter_output_1_sel_wr = SC_LOGIC_0;
    counter_output_1_state = "00";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "axi_stream_counter_range_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst_n, "(port)ap_rst_n");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, count_range_TDATA, "(port)count_range_TDATA");
    sc_trace(mVcdFile, count_range_TVALID, "(port)count_range_TVALID");
    sc_trace(mVcdFile, count_range_TREADY, "(port)count_range_TREADY");
    sc_trace(mVcdFile, counter_output_TDATA, "(port)counter_output_TDATA");
    sc_trace(mVcdFile, counter_output_TVALID, "(port)counter_output_TVALID");
    sc_trace(mVcdFile, counter_output_TREADY, "(port)counter_output_TREADY");
    sc_trace(mVcdFile, ap_return, "(port)ap_return");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_rst_n_inv, "ap_rst_n_inv");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, count_range_0_data_out, "count_range_0_data_out");
    sc_trace(mVcdFile, count_range_0_vld_in, "count_range_0_vld_in");
    sc_trace(mVcdFile, count_range_0_vld_out, "count_range_0_vld_out");
    sc_trace(mVcdFile, count_range_0_ack_in, "count_range_0_ack_in");
    sc_trace(mVcdFile, count_range_0_ack_out, "count_range_0_ack_out");
    sc_trace(mVcdFile, count_range_0_payload_A, "count_range_0_payload_A");
    sc_trace(mVcdFile, count_range_0_payload_B, "count_range_0_payload_B");
    sc_trace(mVcdFile, count_range_0_sel_rd, "count_range_0_sel_rd");
    sc_trace(mVcdFile, count_range_0_sel_wr, "count_range_0_sel_wr");
    sc_trace(mVcdFile, count_range_0_sel, "count_range_0_sel");
    sc_trace(mVcdFile, count_range_0_load_A, "count_range_0_load_A");
    sc_trace(mVcdFile, count_range_0_load_B, "count_range_0_load_B");
    sc_trace(mVcdFile, count_range_0_state, "count_range_0_state");
    sc_trace(mVcdFile, count_range_0_state_cmp_full, "count_range_0_state_cmp_full");
    sc_trace(mVcdFile, counter_output_1_data_out, "counter_output_1_data_out");
    sc_trace(mVcdFile, counter_output_1_vld_in, "counter_output_1_vld_in");
    sc_trace(mVcdFile, counter_output_1_vld_out, "counter_output_1_vld_out");
    sc_trace(mVcdFile, counter_output_1_ack_in, "counter_output_1_ack_in");
    sc_trace(mVcdFile, counter_output_1_ack_out, "counter_output_1_ack_out");
    sc_trace(mVcdFile, counter_output_1_payload_A, "counter_output_1_payload_A");
    sc_trace(mVcdFile, counter_output_1_payload_B, "counter_output_1_payload_B");
    sc_trace(mVcdFile, counter_output_1_sel_rd, "counter_output_1_sel_rd");
    sc_trace(mVcdFile, counter_output_1_sel_wr, "counter_output_1_sel_wr");
    sc_trace(mVcdFile, counter_output_1_sel, "counter_output_1_sel");
    sc_trace(mVcdFile, counter_output_1_load_A, "counter_output_1_load_A");
    sc_trace(mVcdFile, counter_output_1_load_B, "counter_output_1_load_B");
    sc_trace(mVcdFile, counter_output_1_state, "counter_output_1_state");
    sc_trace(mVcdFile, counter_output_1_state_cmp_full, "counter_output_1_state_cmp_full");
    sc_trace(mVcdFile, count_range_TDATA_blk_n, "count_range_TDATA_blk_n");
    sc_trace(mVcdFile, counter_output_TDATA_blk_n, "counter_output_TDATA_blk_n");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, tmp_fu_59_p2, "tmp_fu_59_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, count_range_read_reg_70, "count_range_read_reg_70");
    sc_trace(mVcdFile, ap_block_state1, "ap_block_state1");
    sc_trace(mVcdFile, counterValue_cast_fu_54_p1, "counterValue_cast_fu_54_p1");
    sc_trace(mVcdFile, ap_block_state2_io, "ap_block_state2_io");
    sc_trace(mVcdFile, counterValue_1_fu_64_p2, "counterValue_1_fu_64_p2");
    sc_trace(mVcdFile, counterValue_1_reg_83, "counterValue_1_reg_83");
    sc_trace(mVcdFile, counterValue_reg_43, "counterValue_reg_43");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
    mHdltvinHandle.open("axi_stream_counter_range.hdltvin.dat");
    mHdltvoutHandle.open("axi_stream_counter_range.hdltvout.dat");
}

axi_stream_counter_range::~axi_stream_counter_range() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
}

void axi_stream_counter_range::thread_ap_clk_no_reset_() {
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        count_range_0_sel_rd = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, count_range_0_ack_out.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_1, count_range_0_vld_out.read()))) {
            count_range_0_sel_rd =  (sc_logic) (~count_range_0_sel_rd.read());
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        count_range_0_sel_wr = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, count_range_0_vld_in.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_1, count_range_0_ack_in.read()))) {
            count_range_0_sel_wr =  (sc_logic) (~count_range_0_sel_wr.read());
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        count_range_0_state = ap_const_lv2_0;
    } else {
        if (((esl_seteq<1,1,1>(ap_const_logic_0, count_range_0_vld_in.read()) && 
              esl_seteq<1,1,1>(ap_const_logic_1, count_range_0_ack_out.read()) && 
              esl_seteq<1,2,2>(count_range_0_state.read(), ap_const_lv2_3)) || 
             (esl_seteq<1,1,1>(ap_const_logic_0, count_range_0_vld_in.read()) && 
              esl_seteq<1,2,2>(count_range_0_state.read(), ap_const_lv2_2)))) {
            count_range_0_state = ap_const_lv2_2;
        } else if (((esl_seteq<1,1,1>(ap_const_logic_1, count_range_0_vld_in.read()) && 
                     esl_seteq<1,1,1>(ap_const_logic_0, count_range_0_ack_out.read()) && 
                     esl_seteq<1,2,2>(count_range_0_state.read(), ap_const_lv2_3)) || 
                    (esl_seteq<1,1,1>(ap_const_logic_0, count_range_0_ack_out.read()) && 
                     esl_seteq<1,2,2>(count_range_0_state.read(), ap_const_lv2_1)))) {
            count_range_0_state = ap_const_lv2_1;
        } else if (((esl_seteq<1,1,1>(ap_const_logic_1, count_range_0_vld_in.read()) && 
                     esl_seteq<1,2,2>(count_range_0_state.read(), ap_const_lv2_2)) || 
                    (esl_seteq<1,1,1>(ap_const_logic_1, count_range_0_ack_out.read()) && 
                     esl_seteq<1,2,2>(count_range_0_state.read(), ap_const_lv2_1)) || 
                    (esl_seteq<1,2,2>(count_range_0_state.read(), ap_const_lv2_3) && 
                     !(esl_seteq<1,1,1>(ap_const_logic_1, count_range_0_vld_in.read()) && esl_seteq<1,1,1>(ap_const_logic_0, count_range_0_ack_out.read())) && 
                     !(esl_seteq<1,1,1>(ap_const_logic_0, count_range_0_vld_in.read()) && esl_seteq<1,1,1>(ap_const_logic_1, count_range_0_ack_out.read()))))) {
            count_range_0_state = ap_const_lv2_3;
        } else {
            count_range_0_state = ap_const_lv2_2;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(counter_output_1_ack_in.read(), ap_const_logic_1))) {
        counterValue_reg_43 = counterValue_1_reg_83.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_const_logic_0, count_range_0_vld_out.read())))) {
        counterValue_reg_43 = ap_const_lv31_0;
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        counter_output_1_sel_rd = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, counter_output_1_ack_out.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_1, counter_output_1_vld_out.read()))) {
            counter_output_1_sel_rd =  (sc_logic) (~counter_output_1_sel_rd.read());
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        counter_output_1_sel_wr = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, counter_output_1_vld_in.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_1, counter_output_1_ack_in.read()))) {
            counter_output_1_sel_wr =  (sc_logic) (~counter_output_1_sel_wr.read());
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        counter_output_1_state = ap_const_lv2_0;
    } else {
        if (((esl_seteq<1,1,1>(ap_const_logic_0, counter_output_1_vld_in.read()) && 
              esl_seteq<1,1,1>(ap_const_logic_1, counter_output_1_ack_out.read()) && 
              esl_seteq<1,2,2>(ap_const_lv2_3, counter_output_1_state.read())) || 
             (esl_seteq<1,1,1>(ap_const_logic_0, counter_output_1_vld_in.read()) && 
              esl_seteq<1,2,2>(ap_const_lv2_2, counter_output_1_state.read())))) {
            counter_output_1_state = ap_const_lv2_2;
        } else if (((esl_seteq<1,1,1>(ap_const_logic_1, counter_output_1_vld_in.read()) && 
                     esl_seteq<1,1,1>(ap_const_logic_0, counter_output_1_ack_out.read()) && 
                     esl_seteq<1,2,2>(ap_const_lv2_3, counter_output_1_state.read())) || 
                    (esl_seteq<1,1,1>(ap_const_logic_0, counter_output_1_ack_out.read()) && 
                     esl_seteq<1,2,2>(ap_const_lv2_1, counter_output_1_state.read())))) {
            counter_output_1_state = ap_const_lv2_1;
        } else if (((esl_seteq<1,1,1>(ap_const_logic_1, counter_output_1_vld_in.read()) && 
                     esl_seteq<1,2,2>(ap_const_lv2_2, counter_output_1_state.read())) || 
                    (esl_seteq<1,1,1>(ap_const_logic_1, counter_output_1_ack_out.read()) && 
                     esl_seteq<1,2,2>(ap_const_lv2_1, counter_output_1_state.read())) || 
                    (esl_seteq<1,2,2>(ap_const_lv2_3, counter_output_1_state.read()) && 
                     !(esl_seteq<1,1,1>(ap_const_logic_1, counter_output_1_vld_in.read()) && esl_seteq<1,1,1>(ap_const_logic_0, counter_output_1_ack_out.read())) && 
                     !(esl_seteq<1,1,1>(ap_const_logic_0, counter_output_1_vld_in.read()) && esl_seteq<1,1,1>(ap_const_logic_1, counter_output_1_ack_out.read()))))) {
            counter_output_1_state = ap_const_lv2_3;
        } else {
            counter_output_1_state = ap_const_lv2_2;
        }
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, count_range_0_load_A.read())) {
        count_range_0_payload_A = count_range_TDATA.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, count_range_0_load_B.read())) {
        count_range_0_payload_B = count_range_TDATA.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_const_logic_0, count_range_0_vld_out.read())))) {
        count_range_read_reg_70 = count_range_0_data_out.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && !(esl_seteq<1,1,1>(ap_const_logic_0, counter_output_1_ack_in.read()) || esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_state2_io.read())))) {
        counterValue_1_reg_83 = counterValue_1_fu_64_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, counter_output_1_load_A.read())) {
        counter_output_1_payload_A = counterValue_cast_fu_54_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, counter_output_1_load_B.read())) {
        counter_output_1_payload_B = counterValue_cast_fu_54_p1.read();
    }
}

void axi_stream_counter_range::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void axi_stream_counter_range::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void axi_stream_counter_range::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void axi_stream_counter_range::thread_ap_block_state1() {
    ap_block_state1 = (esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_const_logic_0, count_range_0_vld_out.read()));
}

void axi_stream_counter_range::thread_ap_block_state2_io() {
    ap_block_state2_io = (esl_seteq<1,1,1>(ap_const_lv1_1, tmp_fu_59_p2.read()) && esl_seteq<1,1,1>(ap_const_logic_0, counter_output_1_ack_in.read()));
}

void axi_stream_counter_range::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, counter_output_1_ack_in.read()) || esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_state2_io.read())) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, tmp_fu_59_p2.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, counter_output_1_state.read()[0]))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void axi_stream_counter_range::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void axi_stream_counter_range::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, counter_output_1_ack_in.read()) || esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_state2_io.read())) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, tmp_fu_59_p2.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, counter_output_1_state.read()[0]))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void axi_stream_counter_range::thread_ap_return() {
    ap_return = ap_const_lv32_0;
}

void axi_stream_counter_range::thread_ap_rst_n_inv() {
    ap_rst_n_inv =  (sc_logic) (~ap_rst_n.read());
}

void axi_stream_counter_range::thread_count_range_0_ack_in() {
    count_range_0_ack_in = count_range_0_state.read()[1];
}

void axi_stream_counter_range::thread_count_range_0_ack_out() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_const_logic_0, count_range_0_vld_out.read())))) {
        count_range_0_ack_out = ap_const_logic_1;
    } else {
        count_range_0_ack_out = ap_const_logic_0;
    }
}

void axi_stream_counter_range::thread_count_range_0_data_out() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, count_range_0_sel.read())) {
        count_range_0_data_out = count_range_0_payload_B.read();
    } else {
        count_range_0_data_out = count_range_0_payload_A.read();
    }
}

void axi_stream_counter_range::thread_count_range_0_load_A() {
    count_range_0_load_A = (count_range_0_state_cmp_full.read() & ~count_range_0_sel_wr.read());
}

void axi_stream_counter_range::thread_count_range_0_load_B() {
    count_range_0_load_B = (count_range_0_sel_wr.read() & count_range_0_state_cmp_full.read());
}

void axi_stream_counter_range::thread_count_range_0_sel() {
    count_range_0_sel = count_range_0_sel_rd.read();
}

void axi_stream_counter_range::thread_count_range_0_state_cmp_full() {
    count_range_0_state_cmp_full =  (sc_logic) ((!count_range_0_state.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<1>(): sc_lv<1>(count_range_0_state.read() != ap_const_lv2_1))[0];
}

void axi_stream_counter_range::thread_count_range_0_vld_in() {
    count_range_0_vld_in = count_range_TVALID.read();
}

void axi_stream_counter_range::thread_count_range_0_vld_out() {
    count_range_0_vld_out = count_range_0_state.read()[0];
}

void axi_stream_counter_range::thread_count_range_TDATA_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        count_range_TDATA_blk_n = count_range_0_state.read()[0];
    } else {
        count_range_TDATA_blk_n = ap_const_logic_1;
    }
}

void axi_stream_counter_range::thread_count_range_TREADY() {
    count_range_TREADY = count_range_0_state.read()[1];
}

void axi_stream_counter_range::thread_counterValue_1_fu_64_p2() {
    counterValue_1_fu_64_p2 = (!counterValue_reg_43.read().is_01() || !ap_const_lv31_1.is_01())? sc_lv<31>(): (sc_biguint<31>(counterValue_reg_43.read()) + sc_biguint<31>(ap_const_lv31_1));
}

void axi_stream_counter_range::thread_counterValue_cast_fu_54_p1() {
    counterValue_cast_fu_54_p1 = esl_zext<32,31>(counterValue_reg_43.read());
}

void axi_stream_counter_range::thread_counter_output_1_ack_in() {
    counter_output_1_ack_in = counter_output_1_state.read()[1];
}

void axi_stream_counter_range::thread_counter_output_1_ack_out() {
    counter_output_1_ack_out = counter_output_TREADY.read();
}

void axi_stream_counter_range::thread_counter_output_1_data_out() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, counter_output_1_sel.read())) {
        counter_output_1_data_out = counter_output_1_payload_B.read();
    } else {
        counter_output_1_data_out = counter_output_1_payload_A.read();
    }
}

void axi_stream_counter_range::thread_counter_output_1_load_A() {
    counter_output_1_load_A = (counter_output_1_state_cmp_full.read() & ~counter_output_1_sel_wr.read());
}

void axi_stream_counter_range::thread_counter_output_1_load_B() {
    counter_output_1_load_B = (counter_output_1_sel_wr.read() & counter_output_1_state_cmp_full.read());
}

void axi_stream_counter_range::thread_counter_output_1_sel() {
    counter_output_1_sel = counter_output_1_sel_rd.read();
}

void axi_stream_counter_range::thread_counter_output_1_state_cmp_full() {
    counter_output_1_state_cmp_full =  (sc_logic) ((!counter_output_1_state.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<1>(): sc_lv<1>(counter_output_1_state.read() != ap_const_lv2_1))[0];
}

void axi_stream_counter_range::thread_counter_output_1_vld_in() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, tmp_fu_59_p2.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, counter_output_1_ack_in.read()) || esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_state2_io.read())))) {
        counter_output_1_vld_in = ap_const_logic_1;
    } else {
        counter_output_1_vld_in = ap_const_logic_0;
    }
}

void axi_stream_counter_range::thread_counter_output_1_vld_out() {
    counter_output_1_vld_out = counter_output_1_state.read()[0];
}

void axi_stream_counter_range::thread_counter_output_TDATA() {
    counter_output_TDATA = counter_output_1_data_out.read();
}

void axi_stream_counter_range::thread_counter_output_TDATA_blk_n() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, tmp_fu_59_p2.read())) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()))) {
        counter_output_TDATA_blk_n = counter_output_1_state.read()[1];
    } else {
        counter_output_TDATA_blk_n = ap_const_logic_1;
    }
}

void axi_stream_counter_range::thread_counter_output_TVALID() {
    counter_output_TVALID = counter_output_1_state.read()[0];
}

void axi_stream_counter_range::thread_tmp_fu_59_p2() {
    tmp_fu_59_p2 = (!counterValue_cast_fu_54_p1.read().is_01() || !count_range_read_reg_70.read().is_01())? sc_lv<1>(): (sc_bigint<32>(counterValue_cast_fu_54_p1.read()) < sc_bigint<32>(count_range_read_reg_70.read()));
}

void axi_stream_counter_range::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_const_logic_0, count_range_0_vld_out.read())))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && !(esl_seteq<1,1,1>(ap_const_logic_0, counter_output_1_ack_in.read()) || esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_state2_io.read())) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_fu_59_p2.read()) && esl_seteq<1,1,1>(ap_const_logic_0, counter_output_1_state.read()[0]))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, tmp_fu_59_p2.read()) && !(esl_seteq<1,1,1>(ap_const_logic_0, counter_output_1_ack_in.read()) || esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_state2_io.read())))) {
                ap_NS_fsm = ap_ST_fsm_state3;
            } else {
                ap_NS_fsm = ap_ST_fsm_state2;
            }
            break;
        case 4 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(counter_output_1_ack_in.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        default : 
            ap_NS_fsm = "XXX";
            break;
    }
}

void axi_stream_counter_range::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"ap_rst_n\" :  \"" << ap_rst_n.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"ap_start\" :  \"" << ap_start.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"ap_done\" :  \"" << ap_done.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_idle\" :  \"" << ap_idle.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_ready\" :  \"" << ap_ready.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"count_range_TDATA\" :  \"" << count_range_TDATA.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"count_range_TVALID\" :  \"" << count_range_TVALID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"count_range_TREADY\" :  \"" << count_range_TREADY.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"counter_output_TDATA\" :  \"" << counter_output_TDATA.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"counter_output_TVALID\" :  \"" << counter_output_TVALID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"counter_output_TREADY\" :  \"" << counter_output_TREADY.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_return\" :  \"" << ap_return.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

