// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _axi_stream_counter_range_HH_
#define _axi_stream_counter_range_HH_

#include "systemc.h"
#include "AESL_pkg.h"


namespace ap_rtl {

struct axi_stream_counter_range : public sc_module {
    // Port declarations 13
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst_n;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_in< sc_lv<32> > count_range_TDATA;
    sc_in< sc_logic > count_range_TVALID;
    sc_out< sc_logic > count_range_TREADY;
    sc_out< sc_lv<32> > counter_output_TDATA;
    sc_out< sc_logic > counter_output_TVALID;
    sc_in< sc_logic > counter_output_TREADY;
    sc_out< sc_lv<32> > ap_return;


    // Module declarations
    axi_stream_counter_range(sc_module_name name);
    SC_HAS_PROCESS(axi_stream_counter_range);

    ~axi_stream_counter_range();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    sc_signal< sc_logic > ap_rst_n_inv;
    sc_signal< sc_lv<3> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_lv<32> > count_range_0_data_out;
    sc_signal< sc_logic > count_range_0_vld_in;
    sc_signal< sc_logic > count_range_0_vld_out;
    sc_signal< sc_logic > count_range_0_ack_in;
    sc_signal< sc_logic > count_range_0_ack_out;
    sc_signal< sc_lv<32> > count_range_0_payload_A;
    sc_signal< sc_lv<32> > count_range_0_payload_B;
    sc_signal< sc_logic > count_range_0_sel_rd;
    sc_signal< sc_logic > count_range_0_sel_wr;
    sc_signal< sc_logic > count_range_0_sel;
    sc_signal< sc_logic > count_range_0_load_A;
    sc_signal< sc_logic > count_range_0_load_B;
    sc_signal< sc_lv<2> > count_range_0_state;
    sc_signal< sc_logic > count_range_0_state_cmp_full;
    sc_signal< sc_lv<32> > counter_output_1_data_out;
    sc_signal< sc_logic > counter_output_1_vld_in;
    sc_signal< sc_logic > counter_output_1_vld_out;
    sc_signal< sc_logic > counter_output_1_ack_in;
    sc_signal< sc_logic > counter_output_1_ack_out;
    sc_signal< sc_lv<32> > counter_output_1_payload_A;
    sc_signal< sc_lv<32> > counter_output_1_payload_B;
    sc_signal< sc_logic > counter_output_1_sel_rd;
    sc_signal< sc_logic > counter_output_1_sel_wr;
    sc_signal< sc_logic > counter_output_1_sel;
    sc_signal< sc_logic > counter_output_1_load_A;
    sc_signal< sc_logic > counter_output_1_load_B;
    sc_signal< sc_lv<2> > counter_output_1_state;
    sc_signal< sc_logic > counter_output_1_state_cmp_full;
    sc_signal< sc_logic > count_range_TDATA_blk_n;
    sc_signal< sc_logic > counter_output_TDATA_blk_n;
    sc_signal< sc_logic > ap_CS_fsm_state2;
    sc_signal< sc_lv<1> > tmp_fu_59_p2;
    sc_signal< sc_logic > ap_CS_fsm_state3;
    sc_signal< sc_lv<32> > count_range_read_reg_70;
    sc_signal< bool > ap_block_state1;
    sc_signal< sc_lv<32> > counterValue_cast_fu_54_p1;
    sc_signal< bool > ap_block_state2_io;
    sc_signal< sc_lv<31> > counterValue_1_fu_64_p2;
    sc_signal< sc_lv<31> > counterValue_1_reg_83;
    sc_signal< sc_lv<31> > counterValue_reg_43;
    sc_signal< sc_lv<3> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<3> ap_ST_fsm_state1;
    static const sc_lv<3> ap_ST_fsm_state2;
    static const sc_lv<3> ap_ST_fsm_state3;
    static const sc_lv<32> ap_const_lv32_0;
    static const bool ap_const_boolean_1;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<2> ap_const_lv2_0;
    static const sc_lv<2> ap_const_lv2_2;
    static const sc_lv<2> ap_const_lv2_3;
    static const sc_lv<2> ap_const_lv2_1;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<31> ap_const_lv31_0;
    static const sc_lv<31> ap_const_lv31_1;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state2();
    void thread_ap_CS_fsm_state3();
    void thread_ap_block_state1();
    void thread_ap_block_state2_io();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_ap_return();
    void thread_ap_rst_n_inv();
    void thread_count_range_0_ack_in();
    void thread_count_range_0_ack_out();
    void thread_count_range_0_data_out();
    void thread_count_range_0_load_A();
    void thread_count_range_0_load_B();
    void thread_count_range_0_sel();
    void thread_count_range_0_state_cmp_full();
    void thread_count_range_0_vld_in();
    void thread_count_range_0_vld_out();
    void thread_count_range_TDATA_blk_n();
    void thread_count_range_TREADY();
    void thread_counterValue_1_fu_64_p2();
    void thread_counterValue_cast_fu_54_p1();
    void thread_counter_output_1_ack_in();
    void thread_counter_output_1_ack_out();
    void thread_counter_output_1_data_out();
    void thread_counter_output_1_load_A();
    void thread_counter_output_1_load_B();
    void thread_counter_output_1_sel();
    void thread_counter_output_1_state_cmp_full();
    void thread_counter_output_1_vld_in();
    void thread_counter_output_1_vld_out();
    void thread_counter_output_TDATA();
    void thread_counter_output_TDATA_blk_n();
    void thread_counter_output_TVALID();
    void thread_tmp_fu_59_p2();
    void thread_ap_NS_fsm();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
