int axi_stream_counter (int *);

int main(void)
{
	int i;
	int y;

	for (i = 0; i < 100; i++)
	{
		axi_stream_counter(&y);  // for every clock cycle, it gets data from axi stream and puts it into y 
	}
	return 0; // vivado hls checks the output of the main function.  
	          // if output is 0, the output is fine.  
	          // output matches output generated by the test bench.
}
